### ISSUE TITLE
Make DOB optional on user model 

### ISSUE THREAD

**Issue by CodySwannGT** [gunnertech/ipomor#3]

**Comment by husseinm** [comment]
Are you basically telling me to just remove required: true from the Mongoose model? Or are we also talking about fixing other things such as on the front end?

**Comment by CodySwannGT** [comment]
Bahahaha yeah. Just remove validation from backend.

I'm trying to start you off easy on the new project. Lol

On Monday, August 31, 2015, Mahdi Hussein <notifications@github.com> wrote:

> Are you basically telling me to just remove required: true from the
> Mongoose model? Or are we also talking about fixing other things such as on
> the front end?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/ipomor/issues/3#issuecomment-136537576>.
>


-- 
Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*
